defaults:
  - _self_
  - transform: word_transform

dataset:
  context_col: context
  input_file: data/squad/squad.csv
  output_file: data/squad/squad_augmented.csv

# Batch processing configuration
batch:
  enabled: false          # Enable/disable batch processing
  size: 1000              # Number of rows per batch
  save_intermediate: false # Save intermediate results after each batch
  intermediate_dir: outputs/batches  # Directory for intermediate batch files
  memory_efficient: true  # Enable memory optimization (garbage collection after each batch)