# YAML configuration for the Adversarial transformation using GPT-4o
# Now uses 3 separate OpenAI calls for better accuracy:
# 1. Perturb the original question
# 2. Generate a fake answer for the perturbed question  
# 3. Combine into a fluent distraction sentence
# 4. Check for contradictions and regenerate if needed

transform:
  _target_: src.transformation.adversarial.AdversarialTransformation
  model: "gpt-4o-mini"
  max_tokens: 150  # Reduced since each step is simpler than the original combined prompt
  temperature: 0.7
  insertion_position: "start"  # Options: "start", "end", "random"
  num_transformations: 1
  max_contradiction_attempts: 5  # Maximum attempts to generate non-contradictory distractions
  contradiction_checker:
    _target_: src.utils.contradiction.ContradictionChecker
    model_name: "gpt-4o"  # Use cheaper model for contradiction checking
    temperature: 1.0  # Lower temperature for more consistent contradiction detection

name: |
  adversarial/gpt4o_4step_${transform.transform.model}_tokens_${transform.transform.max_tokens}_temp_${transform.transform.temperature}_pos_${transform.transform.insertion_position}
