# YAML configuration for the Adversarial transformation using GPT-4o
# Now uses 3 separate OpenAI calls for better accuracy:
# 1. Perturb the original question
# 2. Generate a fake answer for the perturbed question  
# 3. Combine into a fluent distraction sentence

transform:
  _target_: src.transformation.adversarial.AdversarialTransformation
  model: "gpt-4o"
  max_tokens: 100  # Reduced since each step is simpler than the original combined prompt
  temperature: 0.5
  insertion_position: "end"  # Options: "start", "end", "random"
  num_transformations: 1

name: |
  adversarial/gpt4o_3step_${transform.transform.model}_tokens_${transform.transform.max_tokens}_temp_${transform.transform.temperature}_pos_${transform.transform.insertion_position}
