# YAML configuration for the Adversarial transformation using GPT-4o-mini
# Uses 3-step process without contradiction checking:
# 1. Perturb the original question
# 2. Generate a fake answer for the perturbed question  
# 3. Combine into a fluent distraction sentence

transform:
  _target_: src.transformation.adversarial.AdversarialTransformation
  model: "gpt-4o-mini"
  max_tokens: 150
  temperature: 0.7
  insertion_position: "start"  # Options: "start", "end", "random"
  num_transformations: 1
  max_contradiction_attempts: 1  # Only one attempt since no contradiction checking
  # contradiction_checker: null  # No contradiction checker provided

name: |
  adversarial/gpt4o_3step_no_checker_${transform.transform.model}_tokens_${transform.transform.max_tokens}_temp_${transform.transform.temperature}_pos_${transform.transform.insertion_position}
