# YAML configuration for the Adversarial transformation using GPT-4o-mini
# Uses 3 separate OpenAI calls for better accuracy:
# 1. Perturb the original question
# 2. Generate a fake answer for the perturbed question  
# 3. Combine into a fluent distraction sentence

transform:
  _target_: src.transformation.adversarial.AdversarialTransformation
  model: "gpt-4o-mini"
  max_tokens: 150  # Reduced since each step is simpler than the original combined prompt
  temperature: 0.7
  insertion_position: "start"  # Options: "start", "end", "random"
  num_transformations: 1
  answerability_checker:
    _target_: src.utils.contradiction.AnswerabilityChecker
    model_name: "gpt-4o"
    temperature: 0.5

name: |
  adversarial/gpt4o_3step_${transform.transform.model}_tokens_${transform.transform.max_tokens}_temp_${transform.transform.temperature}_pos_${transform.transform.insertion_position}
