# YAML configuration for the transformation

transform:
  _target_: src.transformation.character_level_fast.CharacterLevelTransformationFast
  pct_words_to_swap: 0.6
  num_transformations: 1
  max_attempts: 100
  threshold: 0.6

name: |
  text_bugger/text_bugger_${transform.transform.pct_words_to_swap}_percent