# YAML configuration for the transformation

transform:
  _target_: src.transformation.character_level.CharacterLevelTransformation
  pct_words_to_swap: 0.5
  num_transformations: 1

name: |
  text_bugger/text_bugger_${transform.transform.pct_words_to_swap}_percent