# YAML configuration for the Backtranslation transformation (semantic-level)

transform: 
  _target_: src.transformation.semantic_level.BacktranslationTransformation
  chained_back_translation: 5
  num_transformations: 1

name: |
  backtranslation/backtranslation_${transform.transform.chained_back_translation}_times