# YAML configuration for the RandomSequence transformation (sentence-level)

transform:
  _target_: src.transformation.sentence_level.RandomSequenceTransformation
  num_words: 50
  word_length: 10
  insertion_location: 
    _target_: src.transformation.sentence_level.InsertionLocation
    value: spread
  num_transformations: 1

name: |
  random_number_of_words_50_characters_10_spread