# YAML configuration for the RandomSequence transformation (sentence-level)

transformation:
  _target_: src.transformation.sentence_level.RandomSequenceTransformation
  num_words: 50
  word_length: 10
  insertion_location: "spread"  # Options: "start", "end", "random", "spread"
  num_transformations: 10
