# YAML configuration for the RandomSequence transformation (sentence-level)

transform:
  _target_: src.transformation.sentence_level.RandomSequenceTransformation
  num_words: 50
  word_length: 10
  insertion_location: 
    _target_: src.transformation.sentence_level.InsertionLocation
    value: spread
  num_transformations: 1

name: |
  checklist/random_number_of_words_${transform.transform.num_words}_characters_${transform.transform.word_length}_${transform.transform.insertion_location.value}