# YAML configuration for the CLARE transformation (word-level)

transform:
  _target_: src.transformation.word_level.CLARETransformation
  model: "distilroberta-base"
  tokenizer: "distilroberta-base"
  max_candidates: 50
  min_confidence_swap: 0.0005
  min_confidence_insert: 0.0
  min_confidence_merge: 0.005
  threshold: 0.7
  num_transformations: 1

name: |
  clare/clare_candidates_${transform.transform.max_candidates}_swap_${transform.transform.min_confidence_swap}_insert_${transform.transform.min_confidence_insert}_merge_${transform.transform.min_confidence_merge}_threshold_${transform.transform.threshold}