# YAML configuration for the CLARE transformation (word-level)

transform:
  _target_: src.transformation.word_level.CLARETransformation
  model: "distilroberta-base"
  tokenizer: "distilroberta-base"
  max_candidates: 50
  min_confidence_swap: 0.0005
  min_confidence_insert: 0.0
  min_confidence_merge: 0.005
  threshold: 0.7
  num_transformations: 1

name: |
  clare_candidates_50_swap_0_0005_insert_0_0_merge_0_005_threshold_0_7